fix usage on help text from standalone mode
``python -m pyftpdlib.ftpserver`` result in DeprecationWarning

Ex:

``bash
python -m pyftpdlib.ftpserver
/usr/local/lib/python2.7/dist-packages/pyftpdlib/ftpserver.py:53: DeprecationWarning: pyftpdlib.ftpserver module is deprecated
  _depwarn("pyftpdlib.ftpserver module is deprecated")
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pyftpdlib/ftpserver.py", line 88, in <module>
    from pyftpdlib import main
ImportError: cannot import name main

``